title: AarWares
description: AarWares, Bartender
theme: just-the-docs

url: https://aarwares.com

aux_links:
  Bartender Rules: https://aarwares.com/bartender/rules

color_scheme: dark
favicon_ico: "/assets/images/favicon.ico"
