title: AarWares
description: AarWares, Bartender
theme: just-the-docs

url: https://aarwares.com

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

color_scheme: tanbrown
